### ISSUE TITLE
Support for Guice 4.0

### ISSUE THREAD

**Issue by jakub-bochenski** [mycila/guice#11]
I tried using the jsr250 module but got no luck.
Also it seems there are quite a few conflicting classes between guice 4 and  sisu-guice
```
[WARNING] sisu-guice-3.2.3.jar, guice-4.0.jar define 472 overlappping classes: 
[WARNING]   - com.google.inject.Scope
[WARNING]   - com.google.inject.Binding
[WARNING]   - com.google.inject.internal.cglib.core.$EmitUtils$3
[WARNING]   - com.google.inject.spi.TypeConverter
[WARNING]   - com.google.inject.internal.ConstructionProxy
[WARNING]   - com.google.inject.spi.InjectionPoint
[WARNING]   - com.google.inject.internal.cglib.proxy.$FixedValueGenerator
[WARNING]   - com.google.inject.spi.StaticInjectionRequest
[WARNING]   - com.google.inject.internal.cglib.proxy.$DispatcherGenerator
[WARNING]   - com.google.inject.spi.Elements$ElementsAsModule
[WARNING]   - 462 more...
```

**Comment by mgoellnitz** [comment]
I quite successfully worked around this with tweaked dependencies (gradle notation)

```
  compile "com.google.inject:guice:4.0"
  compile "com.google.inject.extensions:guice-servlet:4.0"
  compile "com.google.inject.extensions:guice-multibindings:4.0"

  compile ("com.mycila.guice.extensions:mycila-guice-jsr250:3.6.ga") {
    exclude module: 'sisu-guice'
  }
```

but then ran into trouble using Guice 4.1 and did a patch to migrate this project from sisu-guice to guice (see pull request). If you stick to Guice 4.0 the above might still help.

**Comment by vorburger** [comment]
> it seems there are quite a few conflicting classes between guice 4 and sisu-guice

The `exclude module: 'sisu-guice'` does the trick.

> see pull request

=> https://github.com/mycila/guice/pull/12

@mathieucarbou is @mycila alive? Perhaps you would consider releasing a new version with this fix?

**Comment by mathieucarbou** [comment]
yes it's alive: I do not maintain (no time now) but I am still willing to to some little changes and accept PR :-)

**Comment by mathieucarbou** [comment]
I've just release __4.0.rc1__: it will be in central soon.

**Comment by vorburger** [comment]
@mathieucarbou thanks! FYI I've just tested the 4.0.rc1 - works great for me.
