### ISSUE TITLE
@Resource binding should allow binding by field name

### ISSUE THREAD

**Issue by keeganwitt** [mycila/guice#8]
I was curious why your implementation in `Jsr250KeyProvider`, defaults to binding by the member's type rather than by the member's name when no name is given in the annotation (via `KeyProviderSkeleton. getKey(TypeLiteral<?> injectedType, Field injectedMember, A resourceAnnotation)`).  GuiceyFruit allowed for this in `ResourceMemberProvider` (via `NamedProviderSupport.getValueName(String nameFromAnnotation, Member member)`).

For fields, this would be particularly useful, since it'd let you do things like

    class SomeClass {
        @Resource
        protected String someField
    }
    // ...
    Guice.createInjector(new CloseableModule(), new Jsr250Module(), new AbstractModule() {
        bind(String.class).annotatedWith(Names.named("someField")).toInstance("someValue")
    }

Which avoids the duplication when you want the names to match (which I think is often the case), would more closely match Spring's behavior, and would match the behavior you'd expect (since I'd assume things would be wired by [JNDI name](http://docs.oracle.com/javaee/7/api/javax/annotation/Resource.html#name%28%29), which default to field name for fields).

**Comment by mathieucarbou** [comment]
There is no reason actually ;-) I'll implement it when I'll have some time.

**Comment by keeganwitt** [comment]
I played around with this, and the change seems simple enough.  I can create a PR if you like.  Although, the way I was thinking of implementing this would require a `Named` binding whenever `@Resource` is used (which will bind to the explicit name if given, otherwise it will use the field/parameter name).  But `Resource` seems to me to be a named construct.  So, if the user intended to wire by type, `@Inject` seems a better choice to me.  Can you think of a way to do this without making it a breaking change?  It'd be cool if we could try first by name, then try by type if that fails, but I'm not sure there's a good way to do that.

**Comment by mathieucarbou** [comment]
Oh yes it would be very nice! I won't be able to implement it before this
week-end...

I was thinking of something like this:

https://github.com/mycila/guice/commit/3a2e9e3cdf92cd9c3963253ebbce92c7248240ba#diff-7607dcda1e5344675b1ce9504e887499

it is pushed on master branch, but I don't know yet what impacts it has, if
it works and it has not been tested...

Thanks :-)



[image: ---]
Mathieu Carbou
+1 514-660-4287
<http://t.senalcinco.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX48rl4lbW8p-_cW1pNnvYW5w6vTF56dHMmf6T2vz-02?t=&si=4730178664660992&pi=4fcb7716-5402-4f7c-86b0-aac486248fd8>
mathieu.carbou.me
<http://t.senalcinco.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX48rl4lbW8p-_cW1pNnvYW5w6vTF56dHMmf6T2vz-02?t=http%3A%2F%2Fmathieu.carbou.me%2F&si=4730178664660992&pi=4fcb7716-5402-4f7c-86b0-aac486248fd8>

**Comment by keeganwitt** [comment]
Oh, awesome!  I wasn't sure what your schedule looked like.  I really like the concept, but I think there's an order of operations issue...I'm still looking it over.  In the mean time, I modified the test for both the existing and new behavior (not currently passing): https://github.com/keeganwitt/guice/commit/77870a051eab9d5f1efb5c69e564d5dc0ce65ccd

**Comment by keeganwitt** [comment]
I think I got it working: https://github.com/mycila/guice/pull/9.

**Comment by mathieucarbou** [comment]
Thanks! I'll have a look this week-end and if all works I will release a new version.
